// Generated by mm ldtk types from samples/api-lab/assets/api-lab.ldtk. Do not edit.
import * as LDtk from "minimotor/ldtk";

import type { AssetManifest, Loaded } from "minimotor/assets";

export const levelIds = ["SunnyCommons", "CanopyCrossing", "CrystalCaves"] as const;
export type LevelId = (typeof levelIds)[number];

export const entityTypes = [
  "Solid",
  "OneWay",
  "Ladder",
  "ShallowUp",
  "ShallowDown",
  "SteepUp",
  "SteepDown",
  "Player",
  "Gem",
  "Entry",
  "Exit",
  "Portal",
  "Scenery",
] as const;
export type EntityType = (typeof entityTypes)[number];

export const markerTypes = ["Player", "Gem", "Entry", "Exit"] as const;
export type MarkerType = (typeof markerTypes)[number];

export const tileTypes = [
  "Solid",
  "OneWay",
  "Ladder",
  "ShallowUp",
  "ShallowDown",
  "SteepUp",
  "SteepDown",
] as const;
export type TileType = (typeof tileTypes)[number];

export const portalTypes = ["Portal"] as const;
export type PortalType = (typeof portalTypes)[number];

export const spriteTypes = ["Scenery"] as const;
export type SpriteType = (typeof spriteTypes)[number];

export interface LDtkEntityRef {
  readonly entityIid: string;
  readonly layerIid: string;
  readonly levelIid: string;
  readonly worldIid: string;
}

export interface LDtkGridPoint {
  readonly cx: number;
  readonly cy: number;
}
export interface LDtkTileRef {
  readonly tilesetUid: number;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

export type SceneryAsset =
  | "tree"
  | "bush"
  | "sign"
  | "woodenHouse"
  | "strawHouse"
  | "pine"
  | "palm"
  | "rock"
  | "bigRock"
  | "shrooms"
  | "crate"
  | "bigCrate";
export type PortalTransition = "None" | "Fade" | "WipeLeft" | "WipeRight" | "WipeUp" | "WipeDown";

export interface EntityFields {
  readonly Solid: {};
  readonly OneWay: {};
  readonly Ladder: {};
  readonly ShallowUp: {};
  readonly ShallowDown: {};
  readonly SteepUp: {};
  readonly SteepDown: {};
  readonly Player: {};
  readonly Gem: {};
  readonly Entry: {};
  readonly Exit: {};
  readonly Portal: {
    readonly To: LDtkEntityRef;
    readonly Transition: PortalTransition;
    readonly TransitionMs: number;
  };
  readonly Scenery: {
    readonly Asset: SceneryAsset;
  };
}

export type FieldsOf<T extends EntityType> = EntityFields[T];

export interface LevelFields {
  readonly DisplayName: string;
  readonly CaveRow: number | null;
}

export const entityTypesByLevel = {
  SunnyCommons: [
    "Entry",
    "Gem",
    "Ladder",
    "OneWay",
    "Player",
    "Portal",
    "Scenery",
    "ShallowDown",
    "ShallowUp",
    "Solid",
  ],
  CanopyCrossing: ["Entry", "Gem", "Ladder", "OneWay", "Player", "Portal", "Scenery", "Solid"],
  CrystalCaves: ["Entry", "Gem", "Ladder", "OneWay", "Player", "Portal", "Scenery", "Solid"],
} as const satisfies Record<LevelId, readonly EntityType[]>;

export type EntityIn<L extends LevelId> = (typeof entityTypesByLevel)[L][number];

export const isLevelId = (value: string): value is LevelId =>
  (levelIds as readonly string[]).includes(value);

export const levelAssets = {
  level: new URL("./assets/api-lab.ldtk", import.meta.url).href,
  terrain: new URL("./assets/sunnyland-tileset.png", import.meta.url).href,
} as const satisfies AssetManifest;

export const loadWorld = (assets: Loaded<typeof levelAssets>) =>
  LDtk.world<LevelId, EntityType, EntityFields, LevelFields>(assets.level, {
    image: assets.terrain,
  });
